import { create } from 'zustand'
import { persist } from 'zustand/middleware'

type Language = 'nl' | 'en'

interface Translations {
  [key: string]: string | Translations
}

const translations: Record<Language, Translations> = {
  nl: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      projects: 'Projecten',
      upload: 'Document uploaden',
      documents: 'Alle documenten',
      profiles: 'Profielinstellingen', 
      settings: 'Systeeminstellingen',
      audit: 'Audit log',
      reports: 'Rapporten',
      logout: 'Uitloggen'
    },
    // Common
    common: {
      upload: 'Upload',
      download: 'Download',
      delete: 'Verwijderen',
      edit: 'Bewerken',
      save: 'Opslaan',
      cancel: 'Annuleren',
      close: 'Sluiten',
      back: 'Terug',
      next: 'Volgende',
      previous: 'Vorige',
      loading: 'Laden...',
      search: 'Zoeken',
      filter: 'Filteren',
      sort: 'Sorteren',
      view: 'Bekijken',
      actions: 'Acties',
      status: 'Status',
      name: 'Naam',
      date: 'Datum',
      size: 'Grootte',
      type: 'Type',
      yes: 'Ja',
      no: 'Nee',
      none: 'Geen',
      all: 'Alle',
      or: 'of'
    },
    // App title
    app: {
      title: 'Sensible Docs',
      ssoActive: 'Gemeente SSO Actief',
      session: 'Sessie'
    },
    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welkom bij',
      recentActivity: 'Recente Activiteit',
      quickStats: 'Snelle Statistieken',
      totalProjects: 'Totaal Projecten',
      activeProjects: 'Actieve Projecten',
      documentsProcessed: 'Documenten Verwerkt',
      piiItemsFound: 'PII Items Gevonden',
      recentProjects: 'Recente Projecten',
      recentDocuments: 'Recent verwerkte documenten',
      systemStatus: 'Systeem Status',
      allSystemsOperational: 'Alle systemen operationeel',
      viewAll: 'Alle bekijken',
      piiFound: 'PII Gevonden',
      processedBy: 'Verwerkt door',
      date: 'Datum',
      successfullyAnonymized: 'Succesvol geanonimiseerd',
      inProgress: 'In behandeling',
      averageWaitTime: 'Gemiddeld 4 min wachttijd',
      newUsers: 'nieuwe gebruikers'
    },
    // Projects
    projects: {
      title: 'Projecten',
      subtitle: 'Beheer WOO-verzoeken en documentprojecten',
      createNew: 'Nieuw Project',
      allProjects: 'Alle Projecten',
      myProjects: 'Mijn Projecten',
      active: 'Actief',
      completed: 'Afgerond',
      onHold: 'On Hold',
      archived: 'Gearchiveerd',
      priority: 'Prioriteit',
      urgent: 'Urgent',
      high: 'Hoog',
      medium: 'Gemiddeld',
      low: 'Laag',
      dueDate: 'Deadline',
      progress: 'Voortgang',
      documents: 'Documenten',
      requester: 'Aanvrager',
      department: 'Afdeling',
      requestNumber: 'Verzoek nummer',
      downloadAll: 'Download alles',
      projectDownload: 'Project downloaden',
      documentsCollecting: 'Documenten verzamelen',
      filesPrepping: 'Bestanden voorbereiden',
      zipCreating: 'ZIP-archief maken',
      validatingAnonymization: 'Anonimisering valideren',
      prepDownload: 'Download voorbereiden',
      downloadCompleted: 'Download voltooid!',
      documentsDownloaded: 'documenten succesvol gedownload als ZIP-bestand.',
      searchPlaceholder: 'Zoek projecten...',
      allStatuses: 'Alle statussen',
      allPriorities: 'Alle prioriteiten',
      lastUpdated: 'Laatst bijgewerkt',
      newestFirst: 'Nieuwste eerst',
      nameAZ: 'Naam A-Z',
      closestDeadline: 'Deadline dichtbij',
      project: 'Project',
      status: 'Status',
      actions: 'Acties',
      uploadDocuments: 'Documenten uploaden',
      viewProject: 'Project bekijken',
      moreOptions: 'Meer opties',
      noProjectsFound: 'Geen projecten gevonden',
      adjustFilters: 'Pas je filters aan om meer resultaten te zien.',
      createFirstProject: 'Maak je eerste project aan om te beginnen.',
      createNewProject: 'Nieuw Project Aanmaken',
      days: 'dagen'
    },
    // Upload
    upload: {
      title: 'Document uploaden',
      addToProject: 'Documenten toevoegen aan project',
      uploadingTo: 'Uploaden naar project:',
      dragFiles: 'Sleep bestanden hierheen of klik om te selecteren',
      dropFiles: 'Laat bestanden hier vallen...',
      supportedFormats: 'PDF, Word, of Tekstbestanden (max 50MB)',
      anonymizationProfile: 'Anonimisatieprofiel',
      standardProfile: 'Standaard profiel',
      standardDesc: 'Detecteert alle standaard PII',
      strictProfile: 'Strict profiel',
      strictDesc: 'Extra voorzichtig, detecteert ook potentieel gevoelige informatie',
      minimalProfile: 'Minimaal profiel',
      minimalDesc: 'Alleen direct identificeerbare persoonlijke gegevens',
      fullAnonymization: 'Volledige anonimisatie',
      fullAnonDesc: 'Automatische volledige anonimisatie - direct downloadbare versie',
      selectedFiles: 'Geselecteerde bestanden',
      startProcessing: 'Start verwerking',
      processing: 'Verwerken...',
      readyForProcessing: 'Klaar voor verwerking',
      uploading: 'Uploaden...',
      aiProcessing: 'AI verwerkt document...',
      documentAnonymizing: 'Document wordt geanonimiseerd...',
      completed: 'Voltooid',
      piiItemsFound: 'PII items gevonden',
      fullyAnonymized: 'Volledig geanonimiseerd en gedownload',
      errorOccurred: 'Fout opgetreden',
      addFiles: 'Voeg eerst bestanden toe',
      allProcessed: 'Alle documenten zijn succesvol verwerkt!',
      allAnonymized: 'Alle documenten zijn volledig geanonimiseerd en gedownload!',
      fileTooLarge: 'is te groot (max 50MB)',
      invalidFileType: 'heeft een ongeldig bestandstype',
      noDocuments: 'Nog geen documenten',
      uploadToStart: 'Upload documenten om te beginnen met anonimiseren.',
      uploadFirst: 'Eerste document uploaden'
    },
    // Documents  
    documents: {
      title: 'Alle documenten',
      subtitle: 'Overzicht van alle verwerkte documenten en hun anonimisatiestatus',
      allDocuments: 'Alle Documenten',
      recentDocuments: 'Recente Documenten',
      pendingReview: 'Wacht op review',
      readyForDownload: 'Klaar voor download',
      processing: 'Verwerken',
      error: 'Fout',
      uploadDate: 'Upload datum',
      processedDate: 'Verwerkt datum',
      fileSize: 'Bestandsgrootte',
      piiItems: 'PII items',
      profile: 'Profiel',
      originalFile: 'Origineel bestand',
      anonymizedFile: 'Geanonimiseerd bestand',
      viewDocument: 'Document bekijken',
      downloadOriginal: 'Download origineel',
      downloadAnonymized: 'Download geanonimiseerd',
      searchPlaceholder: 'Zoek op documentnaam of gebruiker...',
      allStatuses: 'Alle statussen',
      totalDocuments: 'Totaal documenten',
      completed: 'Voltooid',
      document: 'Document',
      status: 'Status',
      piiFound: 'PII Gevonden',
      processedBy: 'Verwerkt door',
      date: 'Datum',
      actions: 'Acties',
      items: 'items',
      noPII: 'Geen PII',
      downloadStarted: 'Download gestart voor',
      noDocumentsFound: 'Geen documenten gevonden',
      adjustFilters: 'Pas je filters aan om meer resultaten te zien.',
      uploadFirstDocument: 'Upload je eerste document om aan de slag te gaan.',
      dateNewest: 'Datum (nieuw eerst)',
      dateOldest: 'Datum (oud eerst)'
    },
    // Document Review
    review: {
      title: 'Document Review',
      documentInfo: 'Document Informatie',
      filename: 'Bestandsnaam',
      uploadedBy: 'Geüpload door',
      processingTime: 'Verwerkingstijd',
      seconds: 'seconden',
      quickActions: 'Snelle acties',
      approveAll: 'Alles goedkeuren',
      rejectAll: 'Alles weigeren',
      showOriginal: 'Toon origineel',
      showAnonymized: 'Toon geanonimiseerd',
      downloadOriginal: 'Download origineel',
      downloadAnonymized: 'Download geanonimiseerd',
      positionsDetected: 'posities gedetecteerd',
      piiDetected: 'PII Gedetecteerd',
      approvedItems: 'Goedgekeurde items',
      pendingItems: 'Items in behandeling',
      rejectedItems: 'Afgewezen items',
      totalItems: 'Totaal items',
      approve: 'Goedkeuren',
      reject: 'Afwijzen',
      approved: 'Goedgekeurd',
      rejected: 'Afgewezen',
      confidence: 'Vertrouwen'
    },
    // Profile Settings  
    profiles: {
      title: 'Profielinstellingen',
      subtitle: 'Beheer uw anonimisatieprofielen en PII-detectie instellingen voor optimale WOO-compliance.',
      anonymizationProfiles: 'Anonimisatieprofielen',
      newProfile: 'Nieuw profiel',
      profileName: 'Profielnaam',
      profileNamePlaceholder: 'Bijv. Streng WOO-profiel',
      description: 'Beschrijving',
      descriptionPlaceholder: 'Beschrijf wanneer dit profiel gebruikt moet worden...',
      standard: 'Standaard',
      active: 'Actief',
      inactive: 'Inactief',
      categories: 'categorieën',
      threshold: 'drempel',
      modified: 'Gewijzigd',
      setAsDefault: 'Als standaard instellen',
      duplicate: 'Dupliceren',
      edit: 'Bewerken',
      delete: 'Verwijderen',
      copy: 'kopie',
      defaultCannotDelete: 'Standaardprofiel kan niet worden verwijderd',
      profileCreated: 'Profiel aangemaakt',
      profileSaved: 'Profiel opgeslagen',
      profileDeleted: 'Profiel verwijderd',
      profileCopied: 'Profiel gekopieerd als',
      profileSetAsDefault: 'ingesteld als standaardprofiel',
      nameRequired: 'Naam en beschrijving zijn verplicht',
      status: 'Status',
      detectionSettings: 'Detectie-instellingen',
      detectionThreshold: 'Detectiedrempel',
      maskingStyle: 'Maskering stijl',
      removed: '[VERWIJDERD]',
      replaced: '[VERVANGEN]',
      hash: '###HASH###',
      preserveStructure: 'Documentstructuur behouden',
      logDetections: 'Detecties loggen',
      piiCategories: 'PII Categorieën',
      enabledCategories: 'Ingeschakelde categorieën',
      configureCategories: 'Configureer welke PII-categorieën gedetecteerd moeten worden',
      high: 'Hoog',
      medium: 'Gemiddeld',
      low: 'Laag',
      unknown: 'Onbekend',
      examples: 'Voorbeelden',
      cancel: 'Annuleren',
      saveChanges: 'Wijzigingen opslaan',
      createProfile: 'Profiel aanmaken'
    },
    // Settings
    settings: {
      title: 'Systeeminstellingen',
      subtitle: 'Beheer gebruikers, meldingen en systeemconfiguratie',
      general: 'Algemeen',
      users: 'Gebruikers',
      audit: 'Audit',
      system: 'Systeem',
      security: 'Beveiliging',
      language: 'Taal',
      selectLanguage: 'Selecteer taal',
      dutch: 'Nederlands',
      english: 'Engels',
      notifications: 'Notificaties',
      notificationSettings: 'Meldingsinstellingen',
      emailNotifications: 'E-mail notificaties',
      emailNotificationsDesc: 'Ontvang email notificaties voor belangrijke events',
      uploadNotifications: 'Upload meldingen',
      uploadNotificationsDesc: 'Meldingen wanneer documenten zijn geüpload',
      errorNotifications: 'Fout meldingen',
      errorNotificationsDesc: 'Onmiddellijke meldingen bij systeem fouten',
      weeklyReports: 'Wekelijkse rapporten',
      weeklyReportsDesc: 'Automatische wekelijkse samenvattingen per email',
      securityAlerts: 'Beveiligingswaarschuwingen',
      securityAlertsDesc: 'Kritieke beveiligingsmeldingen en verdachte activiteiten',
      systemAlerts: 'Systeem waarschuwingen',
      auditSettings: 'Audit Instellingen',
      retentionPeriod: 'Bewaarperiode',
      days: 'dagen',
      exportAuditLog: 'Audit log exporteren',
      systemInfo: 'Systeem Informatie',
      version: 'Versie',
      uptime: 'Uptime',
      diskUsage: 'Schijfgebruik',
      memoryUsage: 'Geheugengebruik',
      save: 'Opslaan',
      addUser: 'Gebruiker toevoegen',
      name: 'Naam',
      email: 'Email',
      role: 'Rol',
      status: 'Status',
      lastLogin: 'Laatste login',
      actions: 'Acties',
      active: 'Actief',
      inactive: 'Inactief',
      admin: 'Admin',
      user: 'Gebruiker',
      viewer: 'Bekijker',
      activate: 'Activeren',
      deactivate: 'Deactiveren',
      languageChanged: 'Taal gewijzigd naar',
      languageChangedDutch: 'Taal gewijzigd naar Nederlands',
      languageChangedEnglish: 'Language changed to English'
    },
    // Audit Log
    audit: {
      title: 'Audit log',
      subtitle: 'Complete logging van alle gebruikersacties voor WOO-compliance',
      trail: 'Audit Trail',
      eventType: 'Event Type',
      timestamp: 'Tijdstempel',
      user: 'Gebruiker',
      action: 'Actie',
      details: 'Details',
      export: 'Exporteren',
      refresh: 'Vernieuwen',
      filter: 'Filter',
      filters: 'Filters',
      integrity: 'Integriteit',
      integrityVerify: 'Integriteit verifiëren',
      totalEvents: 'Totaal Events',
      documents: 'Documenten',
      activeUsers: 'Actieve Gebruikers',
      logIntegrity: 'Log Integriteit',
      valid: 'Valid',
      auditEvents: 'Audit Events',
      realTimeLogging: 'Real-time logging van alle gebruikersacties',
      event: 'Event',
      document: 'Document',
      hash: 'Hash',
      allEvents: 'Alle events',
      userActions: 'Gebruikersacties',
      systemEvents: 'Systeem events',
      errorEvents: 'Fout events',
      lastHour: 'Laatste uur',
      lastDay: 'Laatste dag',
      lastWeek: 'Laatste week',
      lastMonth: 'Laatste maand'
    },
    // Reports
    reports: {
      title: 'Rapporten',
      subtitle: 'Inzicht in documentverwerking, compliance en gebruik van het systeem.',
      analytics: 'Rapporten & Analytics',
      generateReport: 'Rapport genereren',
      monthlyReport: 'Maandrapport',
      quarterlyReport: 'Kwartaalrapport',
      yearlyReport: 'Jaarrapport',
      customReport: 'Aangepast rapport',
      dateRange: 'Datumbereik',
      reportType: 'Rapport type',
      includePII: 'PII statistieken inclusief',
      includeUsers: 'Gebruikersactiviteit inclusief',
      includeSystem: 'Systeemstatistieken inclusief',
      generate: 'Genereren',
      download: 'Download rapport',
      downloadReport: 'Rapport downloaden',
      thisMonth: 'Deze maand',
      totalDocuments: 'Totaal documenten',
      successfullyProcessed: 'Succesvol verwerkt',
      avgProcessingTime: 'Gem. verwerkingstijd',
      piiItemsFound: 'PII items gevonden',
      processingPerDay: 'Verwerking per dag',
      piiTypesFound: 'PII types gevonden',
      chartPlaceholder: 'Grafiek wordt hier weergegeven'
    },
    // Error messages
    error: {
      general: 'Er is een fout opgetreden',
      networkError: 'Netwerkfout',
      unauthorized: 'Niet geautoriseerd',
      forbidden: 'Toegang geweigerd',
      notFound: 'Niet gevonden',
      serverError: 'Server fout',
      tryAgain: 'Probeer opnieuw',
      contactSupport: 'Neem contact op met support'
    },
    // Success messages
    success: {
      saved: 'Opgeslagen',
      uploaded: 'Geüpload',
      deleted: 'Verwijderd',
      updated: 'Bijgewerkt',
      processed: 'Verwerkt',
      sent: 'Verzonden',
      completed: 'Voltooid'
    }
  },
  en: {
    // Navigation
    nav: {
      dashboard: 'Dashboard',
      projects: 'Projects',
      upload: 'Upload documents',
      documents: 'All documents',
      profiles: 'Profile settings',
      settings: 'System settings',
      audit: 'Audit log',
      reports: 'Reports',
      logout: 'Sign out'
    },
    // Common
    common: {
      upload: 'Upload',
      download: 'Download',
      delete: 'Delete',
      edit: 'Edit',
      save: 'Save',
      cancel: 'Cancel',
      close: 'Close',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
      loading: 'Loading...',
      search: 'Search',
      filter: 'Filter',
      sort: 'Sort',
      view: 'View',
      actions: 'Actions',
      status: 'Status',
      name: 'Name',
      date: 'Date',
      size: 'Size',
      type: 'Type',
      yes: 'Yes',
      no: 'No',
      none: 'None',
      all: 'All',
      or: 'or'
    },
    // App title
    app: {
      title: 'Sensible Docs',
      ssoActive: 'Municipal SSO Active',
      session: 'Session'
    },
    // Dashboard
    dashboard: {
      title: 'Dashboard',
      welcome: 'Welcome to',
      recentActivity: 'Recent Activity',
      quickStats: 'Quick Statistics',
      totalProjects: 'Total Projects',
      activeProjects: 'Active Projects',
      documentsProcessed: 'Documents Processed',
      piiItemsFound: 'PII Items Found',
      recentProjects: 'Recent Projects',
      recentDocuments: 'Recent processed documents',
      systemStatus: 'System Status',
      allSystemsOperational: 'All systems operational',
      viewAll: 'View all',
      piiFound: 'PII Found',
      processedBy: 'Processed by',
      date: 'Date',
      successfullyAnonymized: 'Successfully anonymized',
      inProgress: 'In progress',
      averageWaitTime: 'Average 4 min wait time',
      newUsers: 'new users'
    },
    // Projects
    projects: {
      title: 'Projects',
      subtitle: 'Manage FOIA requests and document projects',
      createNew: 'New Project',
      allProjects: 'All Projects',
      myProjects: 'My Projects',
      active: 'Active',
      completed: 'Completed',
      onHold: 'On Hold',
      archived: 'Archived',
      priority: 'Priority',
      urgent: 'Urgent',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      dueDate: 'Due Date',
      progress: 'Progress',
      documents: 'Documents',
      requester: 'Requester',
      department: 'Department',
      requestNumber: 'Request number',
      downloadAll: 'Download all',
      projectDownload: 'Downloading project',
      documentsCollecting: 'Collecting documents',
      filesPrepping: 'Preparing files',
      zipCreating: 'Creating ZIP archive',
      validatingAnonymization: 'Validating anonymization',
      prepDownload: 'Preparing download',
      downloadCompleted: 'Download completed!',
      documentsDownloaded: 'documents successfully downloaded as ZIP file.',
      searchPlaceholder: 'Search projects...',
      allStatuses: 'All statuses',
      allPriorities: 'All priorities',
      lastUpdated: 'Last updated',
      newestFirst: 'Newest first',
      nameAZ: 'Name A-Z',
      closestDeadline: 'Closest deadline',
      project: 'Project',
      status: 'Status',
      actions: 'Actions',
      uploadDocuments: 'Upload documents',
      viewProject: 'View project',
      moreOptions: 'More options',
      noProjectsFound: 'No projects found',
      adjustFilters: 'Adjust your filters to see more results.',
      createFirstProject: 'Create your first project to get started.',
      createNewProject: 'Create New Project',
      days: 'days'
    },
    // Upload
    upload: {
      title: 'Upload documents',
      addToProject: 'Add documents to project',
      uploadingTo: 'Uploading to project:',
      dragFiles: 'Drag files here or click to select',
      dropFiles: 'Drop files here...',
      supportedFormats: 'PDF, Word, or Text files (max 50MB)',
      anonymizationProfile: 'Anonymization Profile',
      standardProfile: 'Standard profile',
      standardDesc: 'Detects all standard PII',
      strictProfile: 'Strict profile',
      strictDesc: 'Extra cautious, also detects potentially sensitive information',
      minimalProfile: 'Minimal profile',
      minimalDesc: 'Only directly identifiable personal data',
      fullAnonymization: 'Full anonymization',
      fullAnonDesc: 'Automatic full anonymization - directly downloadable version',
      selectedFiles: 'Selected files',
      startProcessing: 'Start processing',
      processing: 'Processing...',
      readyForProcessing: 'Ready for processing',
      uploading: 'Uploading...',
      aiProcessing: 'AI processing document...',
      documentAnonymizing: 'Document being anonymized...',
      completed: 'Completed',
      piiItemsFound: 'PII items found',
      fullyAnonymized: 'Fully anonymized and downloaded',
      errorOccurred: 'Error occurred',
      addFiles: 'Add files first',
      allProcessed: 'All documents have been successfully processed!',
      allAnonymized: 'All documents have been fully anonymized and downloaded!',
      fileTooLarge: 'is too large (max 50MB)',
      invalidFileType: 'has an invalid file type',
      noDocuments: 'No documents yet',
      uploadToStart: 'Upload documents to start anonymizing.',
      uploadFirst: 'Upload first document'
    },
    // Documents
    documents: {
      title: 'All documents',
      subtitle: 'Overview of all processed documents and their anonymization status',
      allDocuments: 'All Documents',
      recentDocuments: 'Recent Documents',
      pendingReview: 'Pending review',
      readyForDownload: 'Ready for download',
      processing: 'Processing',
      error: 'Error',
      uploadDate: 'Upload date',
      processedDate: 'Processed date',
      fileSize: 'File size',
      piiItems: 'PII items',
      profile: 'Profile',
      originalFile: 'Original file',
      anonymizedFile: 'Anonymized file',
      viewDocument: 'View document',
      downloadOriginal: 'Download original',
      downloadAnonymized: 'Download anonymized',
      searchPlaceholder: 'Search by document name or user...',
      allStatuses: 'All statuses',
      totalDocuments: 'Total documents',
      completed: 'Completed',
      document: 'Document',
      status: 'Status',
      piiFound: 'PII Found',
      processedBy: 'Processed by',
      date: 'Date',
      actions: 'Actions',
      items: 'items',
      noPII: 'No PII',
      downloadStarted: 'Download started for',
      noDocumentsFound: 'No documents found',
      adjustFilters: 'Adjust your filters to see more results.',
      uploadFirstDocument: 'Upload your first document to get started.',
      dateNewest: 'Date (newest first)',
      dateOldest: 'Date (oldest first)'
    },
    // Document Review
    review: {
      title: 'Document Review',
      documentInfo: 'Document Information',
      filename: 'Filename',
      uploadedBy: 'Uploaded by',
      processingTime: 'Processing time',
      seconds: 'seconds',
      quickActions: 'Quick actions',
      approveAll: 'Approve all',
      rejectAll: 'Reject all',
      showOriginal: 'Show original',
      showAnonymized: 'Show anonymized',
      downloadOriginal: 'Download original',
      downloadAnonymized: 'Download anonymized',
      positionsDetected: 'positions detected',
      piiDetected: 'PII Detected',
      approvedItems: 'Approved items',
      pendingItems: 'Pending items',
      rejectedItems: 'Rejected items',
      totalItems: 'Total items',
      approve: 'Approve',
      reject: 'Reject',
      approved: 'Approved',
      rejected: 'Rejected',
      confidence: 'Confidence'
    },
    // Profile Settings  
    profiles: {
      title: 'Profile settings',
      subtitle: 'Manage your anonymization profiles and PII detection settings for optimal FOIA compliance.',
      anonymizationProfiles: 'Anonymization Profiles',
      newProfile: 'New profile',
      profileName: 'Profile name',
      profileNamePlaceholder: 'E.g. Strict FOIA profile',
      description: 'Description',
      descriptionPlaceholder: 'Describe when this profile should be used...',
      standard: 'Default',
      active: 'Active',
      inactive: 'Inactive',
      categories: 'categories',
      threshold: 'threshold',
      modified: 'Modified',
      setAsDefault: 'Set as default',
      duplicate: 'Duplicate',
      edit: 'Edit',
      delete: 'Delete',
      copy: 'copy',
      defaultCannotDelete: 'Default profile cannot be deleted',
      profileCreated: 'Profile created',
      profileSaved: 'Profile saved',
      profileDeleted: 'Profile deleted',
      profileCopied: 'Profile copied as',
      profileSetAsDefault: 'set as default profile',
      nameRequired: 'Name and description are required',
      status: 'Status',
      detectionSettings: 'Detection Settings',
      detectionThreshold: 'Detection threshold',
      maskingStyle: 'Masking style',
      removed: '[REMOVED]',
      replaced: '[REPLACED]',
      hash: '###HASH###',
      preserveStructure: 'Preserve document structure',
      logDetections: 'Log detections',
      piiCategories: 'PII Categories',
      enabledCategories: 'Enabled categories',
      configureCategories: 'Configure which PII categories should be detected',
      high: 'High',
      medium: 'Medium',
      low: 'Low',
      unknown: 'Unknown',
      examples: 'Examples',
      cancel: 'Cancel',
      saveChanges: 'Save changes',
      createProfile: 'Create profile'
    },
    // Settings
    settings: {
      title: 'System settings',
      subtitle: 'Manage users, notifications and system configuration',
      general: 'General',
      users: 'Users',
      audit: 'Audit',
      system: 'System',
      security: 'Security',
      language: 'Language',
      selectLanguage: 'Select language',
      dutch: 'Dutch',
      english: 'English',
      notifications: 'Notifications',
      notificationSettings: 'Notification Settings',
      emailNotifications: 'Email notifications',
      emailNotificationsDesc: 'Receive email notifications for important events',
      uploadNotifications: 'Upload notifications',
      uploadNotificationsDesc: 'Notifications when documents are uploaded',
      errorNotifications: 'Error notifications',
      errorNotificationsDesc: 'Immediate notifications for system errors',
      weeklyReports: 'Weekly reports',
      weeklyReportsDesc: 'Automatic weekly summaries via email',
      securityAlerts: 'Security alerts',
      securityAlertsDesc: 'Critical security notifications and suspicious activities',
      systemAlerts: 'System alerts',
      auditSettings: 'Audit Settings',
      retentionPeriod: 'Retention period',
      days: 'days',
      exportAuditLog: 'Export audit log',
      systemInfo: 'System Information',
      version: 'Version',
      uptime: 'Uptime',
      diskUsage: 'Disk usage',
      memoryUsage: 'Memory usage',
      save: 'Save',
      addUser: 'Add user',
      name: 'Name',
      email: 'Email',
      role: 'Role',
      status: 'Status',
      lastLogin: 'Last login',
      actions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      admin: 'Admin',
      user: 'User',
      viewer: 'Viewer',
      activate: 'Activate',
      deactivate: 'Deactivate',
      languageChanged: 'Language changed to',
      languageChangedDutch: 'Taal gewijzigd naar Nederlands',
      languageChangedEnglish: 'Language changed to English'
    },
    // Audit Log
    audit: {
      title: 'Audit log',
      subtitle: 'Complete logging of all user actions for FOIA compliance',
      trail: 'Audit Trail',
      eventType: 'Event Type',
      timestamp: 'Timestamp',
      user: 'User',
      action: 'Action',
      details: 'Details',
      export: 'Export',
      refresh: 'Refresh',
      filter: 'Filter',
      filters: 'Filters',
      integrity: 'Integrity',
      integrityVerify: 'Verify integrity',
      totalEvents: 'Total Events',
      documents: 'Documents',
      activeUsers: 'Active Users',
      logIntegrity: 'Log Integrity',
      valid: 'Valid',
      auditEvents: 'Audit Events',
      realTimeLogging: 'Real-time logging of all user actions',
      event: 'Event',
      document: 'Document',
      hash: 'Hash',
      allEvents: 'All events',
      userActions: 'User actions',
      systemEvents: 'System events',
      errorEvents: 'Error events',
      lastHour: 'Last hour',
      lastDay: 'Last day',
      lastWeek: 'Last week',
      lastMonth: 'Last month'
    },
    // Reports
    reports: {
      title: 'Reports',
      subtitle: 'Insights into document processing, compliance and system usage.',
      analytics: 'Reports & Analytics',
      generateReport: 'Generate report',
      monthlyReport: 'Monthly report',
      quarterlyReport: 'Quarterly report',
      yearlyReport: 'Yearly report',
      customReport: 'Custom report',
      dateRange: 'Date range',
      reportType: 'Report type',
      includePII: 'Include PII statistics',
      includeUsers: 'Include user activity',
      includeSystem: 'Include system statistics',
      generate: 'Generate',
      download: 'Download report',
      downloadReport: 'Download report',
      thisMonth: 'This month',
      totalDocuments: 'Total documents',
      successfullyProcessed: 'Successfully processed',
      avgProcessingTime: 'Avg. processing time',
      piiItemsFound: 'PII items found',
      processingPerDay: 'Processing per day',
      piiTypesFound: 'PII types found',
      chartPlaceholder: 'Chart will be displayed here'
    },
    // Error messages
    error: {
      general: 'An error occurred',
      networkError: 'Network error',
      unauthorized: 'Unauthorized',
      forbidden: 'Access denied',
      notFound: 'Not found',
      serverError: 'Server error',
      tryAgain: 'Try again',
      contactSupport: 'Contact support'
    },
    // Success messages
    success: {
      saved: 'Saved',
      uploaded: 'Uploaded',
      deleted: 'Deleted',
      updated: 'Updated',
      processed: 'Processed',
      sent: 'Sent',
      completed: 'Completed'
    }
  }
}

interface LanguageStore {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set, get) => ({
      language: 'nl',
      setLanguage: (lang: Language) => set({ language: lang }),
      t: (key: string): string => {
        const { language } = get()
        const keys = key.split('.')
        let value: any = translations[language]
        
        for (const k of keys) {
          if (value && typeof value === 'object' && k in value) {
            value = value[k]
          } else {
            // Fallback to Dutch if English translation is missing
            value = translations.nl
            for (const fallbackKey of keys) {
              if (value && typeof value === 'object' && fallbackKey in value) {
                value = value[fallbackKey]
              } else {
                return `[${key}]` // Show missing translation key
              }
            }
            break
          }
        }
        
        return typeof value === 'string' ? value : `[${key}]`
      }
    }),
    {
      name: 'sensible-docs-language'
    }
  )
) 